Title: Alnm-06
logo: docs/assets/Imagem do WhatsApp de 2025-05-11 Ã (s) 12.16.58_42970d1e.jpg
Description: Estudante
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
